SRC_DIR = src
BUILD_DIR = src
CC = g++
SRC_FILE =  hw2.cpp 
OBJ_NAME = game
LIBRARY_PATH = -lpthread 
COMPLE_FLAGS = -std=c++11

all:
	$(CC) $(COMPLE_FLAGS)  $(SRC_FILE) -o $(OBJ_NAME) $(LIBRARY_PATH)

clean:
	rm -f $(OBJ_NAME)